### ISSUE TITLE
Texto en figuras - cap 1

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#1]
Las figuras 1.1 y 1.2 tienen el texto sobre la misma fotografía, y si bien es legible, quedaría mas prolijo que el texto estuviera a un costado, apuntando con una flecha al rectángulo de la figura.

**Comment by mauriciobarroso** [comment]
Quedaría mejor como dices, lo corrijo el fin de semana

**Comment by mauriciobarroso** [comment]
Corregido
