### ISSUE TITLE
Párrafo muy corto

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#2]
En el archivo **emmon-memory/Chapters/Chapter1.tex** linea 69 (según el archivo aquí en el repo), hay un párrafo de una única oración, referenciando a una figura.

Quedaría mejor si se pudiera integrar con alguno de los párrafos adyacentes.

**Comment by mauriciobarroso** [comment]
Tienes razón, corregido
