### ISSUE TITLE
Imagenes flotantes en otras secciones

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#3]
En el archivo **emmon-memory/Chapters/Chapter1.tex** se pueden agregar comandos **/FloatBarrier** para que las imágenes, si bien flotantes, queden confinadas a sus propias secciones. Ayuda a la legibilidad, y no tiene un efecto apreciable por el agregado de espacios en blanco, dado que los trabajos no se imprimen a fin de cuentas, solo se presenta la memoria en digital.

_Ver figura 1.5 - traspasa sección_

**Comment by mauriciobarroso** [comment]
Al unir el párrafo corto de la línea 69 con el párrafo anterior, el error de la figura 1.5 se corrigió solo. Tendre en cuenta los comandos que me comentas para los siguientes capítulos.
