### ISSUE TITLE
Cambiar designación - Requerimientos

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#4]
En la sección 2.1 Requerimientos se hace mención de requerimientos "no funcionales". Creo que seria bueno encontrar otra forma de expresar esto de manera mas elegante: el porque de la designación es comprensible, pero da una sensación negativa. 
Ejemplos: Requerimientos de documentación (manual); Requerimientos de producción (costos).

**Comment by mauriciobarroso** [comment]
Corregido
