### ISSUE TITLE
Seccion 2.2.1 - Conversor Optico-Electrico

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#6]
En el segundo párrafo de esta sección se hace mención de que "_El valor de la relación entre los pulsos emitidos y el consumo eléctrico es un parámetro intrínseco del medidor, que varía según el modelo y la firma que lo fabrica._"

Es un tecnicismo en realidad, pero los valores o propiedades intrínsecas dependen del material y son invariantes. Por ejemplo, la temperatura de fusión de cierta aleación que se utiliza en fusibles de corriente. Esta temperatura es en realidad una propiedad intrínseca del material, porque no depende de otra cosa sino del mismo.

Aquí seria bueno hablar de "_un parámetro que varía según el modelo de medidor y la firma que lo fabrica_"

**Comment by mauriciobarroso** [comment]
Correción aplicada. Queda mejor como lo propones.
