### ISSUE TITLE
Seccion 3.1.2 - Transceptor LoRa

### ISSUE THREAD

**Issue by gonzaloesanchez** [mauriciobarroso/emmon-memory#9]
Cuando se habla del decreto supremo (y en general de leyes, decretos y demás documentos de la misma índole) se debe hacer referencia a la fecha de **publicación**. Es mas propio que hablar de _lanzamiento_ dado que un producto se lanza al mercado, pero no así una ley/decreto/normativas

**Comment by mauriciobarroso** [comment]
Corregido. Se elimina la palabra "lanzado" y se agraga la fecha del decreto.
